DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) NULL,
  PHONE VARCHAR(12) NOT NULL,
  FROM_LOCATION VARCHAR(250) NOT NULL,
  TO_LOCATION VARCHAR(250) NOT NULL,
  CURRENTTIME TIME() NOT NULL
);

INSERT INTO users (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, FROM_LOCATION, TO_LOCATION, CURRENTTIME) VALUES
  (1, 'first', 'last 1', 'abc1@gmail.com'),
  (2, 'first', 'last 2', 'abc2@gmail.com'),
  (3, 'first', 'last 3', 'abc3@gmail.com');